// auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const PASSWORD_RECOVERY = 'PASSWORD_RECOVERY';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// users
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
export const SET_USER_QUERIES = 'SET_USER_QUERIES';

// courses
export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';
export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAILURE = 'GET_COURSES_FAILURE';
export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAILURE = 'GET_COURSE_FAILURE';
export const EDIT_COURSE_REQUEST = 'EDIT_COURSE';
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS';
export const EDIT_COURSE_FAILURE = 'EDIT_COURSE_FAILURE';
export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';
export const SET_COURSE_QUERIES = 'SET_COURSE_QUERIES';

// enrollments
export const CREATE_ENROLL_REQUEST = 'CREATE_ENROLL_REQUEST';
export const CREATE_ENROLL_SUCCESS = 'CREATE_ENROLL_SUCCESS';
export const CREATE_ENROLL_FAILURE = 'CREATE_ENROLL_FAILURE';
export const GET_ENROLLMENTS_REQUEST = 'GET_ENROLLMENTS_REQUEST';
export const GET_ENROLLMENTS_SUCCESS = 'GET_ENROLLMENTS_SUCCESS';
export const GET_ENROLLMENTS_FAILURE = 'GET_ENROLLMENTS_FAILURE';
export const GET_COURSE_ENROLLMENTS_REQUEST = 'GET_COURSE_ENROLLMENTS_REQUEST';
export const GET_COURSE_ENROLLMENTS_SUCCESS = 'GET_COURSE_ENROLLMENTS_SUCCESS';
export const GET_COURSE_ENROLLMENTS_FAILURE = 'GET_COURSE_ENROLLMENTS_FAILURE';
export const CANCEL_ENROLLMENT_REQUEST = 'CANCEL_ENROLLMENT_REQUEST';
export const CANCEL_ENROLLMENT_SUCCESS = 'CANCEL_ENROLLMENT_SUCCESS';
export const CANCEL_ENROLLMENT_FAILURE = 'CANCEL_ENROLLMENT_FAILURE';
export const SET_ENROLLMENT_QUERIES = 'SET_ENROLLMENT_QUERIES';


// grades
export const POST_GRADE_REQUEST = 'POST_GRADE_REQUEST';
export const POST_GRADE_SUCCESS = 'POST_GRADE_SUCCESS';
export const POST_GRADE_FAILURE = 'POST_GRADE_FAILURE';
export const GET_GRADES_REQUEST = 'GET_GRADES_REQUEST';
export const GET_GRADES_SUCCESS = 'GET_GRADES_SUCCESS';
export const GET_GRADES_FAILURE = 'GET_GRADES_FAILURE';
export const EDIT_GRADE_REQUEST = 'EDIT_GRADE';
export const EDIT_GRADE_SUCCESS = 'EDIT_GRADE_SUCCESS';
export const EDIT_GRADE_FAILURE = 'EDIT_GRADE_FAILURE';
export const SET_GRADE_QUERIES = 'SET_GRADE_QUERIES';

// generales
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_SELECTED = 'CLEAR_SELECTED';
